### ISSUE TITLE
No title when value is zero

### ISSUE THREAD

**Issue by Shomrat-Gil** [kevinkhill/lavacharts-examples#2]
When changing one of the values to 0 the title not showing on the chart:
$reasons->addColumn('string', 'Reasons')
                ->addColumn('number', 'Percent')
                ->addRow(array('Check Reviews', 5))
                ->addRow(array('Watch Trailers', 2))
                ->addRow(array('See Actors Other Work', 4))
                ->addRow(array('Settle Argument', 89));  
on this example the pie shows all 4 titles, each points to the slice color, but if you`ll change 
->addRow(array('Check Reviews', 5))
into
->addRow(array('Check Reviews', 0))
Since there is no slice to show, the title "Check Reviews" not showing, since its part of the main list all titles are expected to show.
Is there a way to force 0 value titles to be visible?
Thanks

**Comment by kevinkhill** [comment]
Maybe try `legend.maxLines`?

According to [Google's Docs](https://developers.google.com/chart/interactive/docs/gallery/piechart#configuration-options):
Maximum number of lines in the legend. Set this to a number greater than one to add lines to your legend. Note: The exact logic used to determine the actual number of lines rendered is still in flux.

This option currently works only when legend.position is 'top'.

**Comment by Shomrat-Gil** [comment]
Thanks for the reply, tried with adding:
'legend' => [ 'position'=>'top', 'maxLines'=>4, ] ,
But, I`m not looking to limit the number of legend, I'm trying to get them all display even if one or more value is zero ->addRow(array('Check Reviews', 0)).
Not sure that it can be done, because I tried on google sample and it has the same issue.

**Comment by kevinkhill** [comment]
super stale! please post again if needed
