### ISSUE TITLE
Found an Error in your GougeChart Controller

### ISSUE THREAD

**Issue by Alihaile** [kevinkhill/lavacharts-examples#3]
Please Correct this Line:
// Lava::GaugeChart('Temps')

Correct is:
// Lava::GaugeChart('Temps',$temps)

**Comment by kevinkhill** [comment]
Actually this whole repo is out of date. All the controllers need to be updated for the new syntax. I do not plan on fixing this anytime soon since I don't even have time to work on the main Lavacharts repo, sorry.

**Comment by kevinkhill** [comment]
I'm happy to accept pull requests if you feel like updating them 😄
